//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika3.en
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_orders { get; set; }
        public System.DateTime DataPokupki { get; set; }
        public decimal Price { get; set; }
        public int clients_ID { get; set; }
        public int mesto_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Mesto Mesto { get; set; }
    }
}
